travis:
  secure:
    BINSTAR_TOKEN: rGxB31semqSEdUpPOeQsPMkaDzYjZHL4khqJIAJ3CV9fBgAR9NiQ3kmg10fxDLFqLkbU60G0qQ0ZMqs0Yib0NAc2rr8D09O/lPPbmEZT/o2bsU3LA5N2HENYEk0VtEuoA5BJq2kqq7BEKT1hr+5TH5KbF7mLZpuXoPH8QeK4ApuN6XqQVUK6uDgZbE5XMxZT8NmUBSqcb3ihADONSaIyX6uyPR8eAfvfqHIfvW5b8kcvaGWZGuKF9JMKlcgOFLS6+a5DZi0hCa08BrR7sZNEeoU6X8+pnKPuT+yJxFZhe13Es96Fc3P1V2tFWi3SfmgsCU5/M5Op1aT6QEWUOcbtQcmYbDuzABaI6T2zUmItRgIX2m9ACeHBBNfUwH7ai4rQAi842JeYw5vR3HtaRk/8I+nah1MpwbnKH4C7a+YR+Zmkx7te4sZqnElm1SaT40Jsybj17a8KO3YFKNhbQcGZ+MT9sETJBiSc1sS6+mKYi2ZWTgbOqkrusGLU6pC8Ueoy/ltFZ4tn6aIOthFPyPj4KAGaHovfc86UU2mrq8fCoUiKfueWQxxqKxXi2BLhTQWUq3Z+WsjCcyzh4/6E+d77nwnNyu6FGbanyXakv+YlVWqPwI3gOquAKwUUd3p7tg3oHnj/XSHPC6wRZT6HlO3clcJDNwxBRM24y5Sepj2V4tU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
